
```{r session-duration, echo=FALSE}
report_render_duration_in_seconds <- round(as.numeric(difftime(Sys.time(), report_render_start_time, units="secs")))
```

Report rendered by `r Sys.info()["user"]` at `r strftime(Sys.time(), "%Y-%m-%d, %H:%M %z")` in `r report_render_duration_in_seconds` seconds.

For the sake of documentation and reproducibility, the current report was rendered in the following environment.  Click the line below to expand.  But you'll probably regret it.

<details>
<summary>Environment <span class="glyphicon glyphicon-plus-sign"></span></summary>
```{r session-info-2, echo=FALSE}
sessioninfo::platform_info() |>
  base::unlist() |> 
  tibble::enframe(
    name = "setting"
  ) |> 
  kableExtra::kbl(
    caption = "Session Info"
  ) |>
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width        = FALSE,
    position          = "left"
  )

sessioninfo::package_info(include_base = TRUE, pkgs = "loaded") |> 
  dplyr::select(
    -path,
    -loadedpath,
    -is_base,
    -library,
    # -md5ok,
  ) |>
  kableExtra::kbl(
    caption = "Packages"
  ) |>
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width        = FALSE,
    position          = "left"
  )

sessioninfo::external_info() |>
  base::unlist() |> 
  tibble::enframe(
    name = "setting"
  ) |> 
  kableExtra::kbl(
    caption = "External Info"
  ) |>
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width        = FALSE,
    position          = "left"
  )
```
</details>
